#!/usr/bin/expect
set timeout 10
set USER [lindex $argv 0]
set IP [lindex $argv 1]
set PASS [lindex $argv 2]
spawn ssh $USER\@$IP
expect {
	"(yes/no)?"
	{send "yes\n";exp_continue}
	"password:"
	{send "$PASS\n"}
}
expect "Last login:"
interact
